//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace metering.core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OmicronStringCmd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OmicronStringCmd() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("metering.core.Resources.OmicronStringCmd", typeof(OmicronStringCmd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amp:def(clrnooff).
        /// </summary>
        public static string amp_def_init {
            get {
                return ResourceManager.GetString("amp_def_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amp:range(i(1),{0}).
        /// </summary>
        public static string amp_range_current {
            get {
                return ResourceManager.GetString("amp_range_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amp:range(v(1),{0}).
        /// </summary>
        public static string amp_range_voltage {
            get {
                return ResourceManager.GetString("amp_range_voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amp:route(i(1),14).
        /// </summary>
        public static string amp_route_current {
            get {
                return ResourceManager.GetString("amp_route_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amp:route(clrnooff).
        /// </summary>
        public static string amp_route_init {
            get {
                return ResourceManager.GetString("amp_route_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amp:route(v(1),9).
        /// </summary>
        public static string amp_route_voltage {
            get {
                return ResourceManager.GetString("amp_route_voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amp:scan?.
        /// </summary>
        public static string amp_scan {
            get {
                return ResourceManager.GetString("amp_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out:ana:off.
        /// </summary>
        public static string out_analog_outputOff {
            get {
                return ResourceManager.GetString("out_analog_outputOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out:ana:on.
        /// </summary>
        public static string out_analog_outputOn {
            get {
                return ResourceManager.GetString("out_analog_outputOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out:ana:pmode(abs).
        /// </summary>
        public static string out_analog_pmode {
            get {
                return ResourceManager.GetString("out_analog_pmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out:ana:{0}({1}):a({2});p({3});f({4});wav(sin).
        /// </summary>
        public static string out_analog_setOutput {
            get {
                return ResourceManager.GetString("out_analog_setOutput", resourceCulture);
            }
        }
    }
}
