//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace metering.core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("metering.core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Test.
        /// </summary>
        public static string addNewTest {
            get {
                return ResourceManager.GetString("addNewTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancelTest {
            get {
                return ResourceManager.GetString("cancelTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal Analog Values:.
        /// </summary>
        public static string global_nominal_analog_header {
            get {
                return ResourceManager.GetString("global_nominal_analog_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal Current (A):.
        /// </summary>
        public static string global_nominal_current {
            get {
                return ResourceManager.GetString("global_nominal_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal Delta:.
        /// </summary>
        public static string global_nominal_delta {
            get {
                return ResourceManager.GetString("global_nominal_delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal Frequency (Hz):.
        /// </summary>
        public static string global_nominal_frequency {
            get {
                return ResourceManager.GetString("global_nominal_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string global_nominal_phase_balance {
            get {
                return ResourceManager.GetString("global_nominal_phase_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal Current Phase:.
        /// </summary>
        public static string global_nominal_phase_current {
            get {
                return ResourceManager.GetString("global_nominal_phase_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal Voltage Phase:.
        /// </summary>
        public static string global_nominal_phase_voltage {
            get {
                return ResourceManager.GetString("global_nominal_phase_voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0°.
        /// </summary>
        public static string global_nominal_phase_zero {
            get {
                return ResourceManager.GetString("global_nominal_phase_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal Test Values:.
        /// </summary>
        public static string global_nominal_test_values {
            get {
                return ResourceManager.GetString("global_nominal_test_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal Voltage (V):.
        /// </summary>
        public static string global_nominal_voltage {
            get {
                return ResourceManager.GetString("global_nominal_voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IL5.
        /// </summary>
        public static string header_current_5 {
            get {
                return ResourceManager.GetString("header_current_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IL6.
        /// </summary>
        public static string header_current_6 {
            get {
                return ResourceManager.GetString("header_current_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta.
        /// </summary>
        public static string header_delta {
            get {
                return ResourceManager.GetString("header_delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta (A).
        /// </summary>
        public static string header_delta_current {
            get {
                return ResourceManager.GetString("header_delta_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta (Hz).
        /// </summary>
        public static string header_delta_frequency {
            get {
                return ResourceManager.GetString("header_delta_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta (°).
        /// </summary>
        public static string header_delta_phase {
            get {
                return ResourceManager.GetString("header_delta_phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta (V).
        /// </summary>
        public static string header_delta_voltage {
            get {
                return ResourceManager.GetString("header_delta_voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwell Time (sec).
        /// </summary>
        public static string header_dwell_time {
            get {
                return ResourceManager.GetString("header_dwell_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency (Hz).
        /// </summary>
        public static string header_frequency {
            get {
                return ResourceManager.GetString("header_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string header_from {
            get {
                return ResourceManager.GetString("header_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From (A).
        /// </summary>
        public static string header_from_current {
            get {
                return ResourceManager.GetString("header_from_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From (Hz).
        /// </summary>
        public static string header_from_frequency {
            get {
                return ResourceManager.GetString("header_from_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From (°).
        /// </summary>
        public static string header_from_phase {
            get {
                return ResourceManager.GetString("header_from_phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From (V).
        /// </summary>
        public static string header_from_voltage {
            get {
                return ResourceManager.GetString("header_from_voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnitude(A).
        /// </summary>
        public static string header_magnitude_current {
            get {
                return ResourceManager.GetString("header_magnitude_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnitude(V).
        /// </summary>
        public static string header_magnitude_voltage {
            get {
                return ResourceManager.GetString("header_magnitude_voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Value.
        /// </summary>
        public static string header_max_value {
            get {
                return ResourceManager.GetString("header_max_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Duration.
        /// </summary>
        public static string header_measurement_duration {
            get {
                return ResourceManager.GetString("header_measurement_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Interval (msec).
        /// </summary>
        public static string header_measurement_interval {
            get {
                return ResourceManager.GetString("header_measurement_interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Value.
        /// </summary>
        public static string header_min_value {
            get {
                return ResourceManager.GetString("header_min_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase (°).
        /// </summary>
        public static string header_phase {
            get {
                return ResourceManager.GetString("header_phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string header_progress {
            get {
                return ResourceManager.GetString("header_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string header_register {
            get {
                return ResourceManager.GetString("header_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal.
        /// </summary>
        public static string header_signal {
            get {
                return ResourceManager.GetString("header_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Delay Time (min).
        /// </summary>
        public static string header_start_delay_time {
            get {
                return ResourceManager.GetString("header_start_delay_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Measurement Delay (sec).
        /// </summary>
        public static string header_start_measurement_delay {
            get {
                return ResourceManager.GetString("header_start_measurement_delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Value.
        /// </summary>
        public static string header_test_value {
            get {
                return ResourceManager.GetString("header_test_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string header_to {
            get {
                return ResourceManager.GetString("header_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To (A).
        /// </summary>
        public static string header_to_current {
            get {
                return ResourceManager.GetString("header_to_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To (Hz).
        /// </summary>
        public static string header_to_frequency {
            get {
                return ResourceManager.GetString("header_to_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To (°).
        /// </summary>
        public static string header_to_phase {
            get {
                return ResourceManager.GetString("header_to_phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To (V).
        /// </summary>
        public static string header_to_voltage {
            get {
                return ResourceManager.GetString("header_to_voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1.
        /// </summary>
        public static string header_voltage_1 {
            get {
                return ResourceManager.GetString("header_voltage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2.
        /// </summary>
        public static string header_voltage_2 {
            get {
                return ResourceManager.GetString("header_voltage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V3.
        /// </summary>
        public static string header_voltage_3 {
            get {
                return ResourceManager.GetString("header_voltage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V4.
        /// </summary>
        public static string header_voltage_4 {
            get {
                return ResourceManager.GetString("header_voltage_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beckwith Logo.
        /// </summary>
        public static string logo_alt_name {
            get {
                return ResourceManager.GetString("logo_alt_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max. test value.
        /// </summary>
        public static string modal_max_test_value {
            get {
                return ResourceManager.GetString("modal_max_test_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min. test value.
        /// </summary>
        public static string modal_min_test_value {
            get {
                return ResourceManager.GetString("modal_min_test_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use tab_voltage, tab_current and tab_frequency values..
        /// </summary>
        public static string modal_options {
            get {
                return ResourceManager.GetString("modal_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test duration (hr.).
        /// </summary>
        public static string modal_test_duration {
            get {
                return ResourceManager.GetString("modal_test_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test interval (sec.).
        /// </summary>
        public static string modal_test_interval {
            get {
                return ResourceManager.GetString("modal_test_interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify/add a register.
        /// </summary>
        public static string modal_title {
            get {
                return ResourceManager.GetString("modal_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string modal_update {
            get {
                return ResourceManager.GetString("modal_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection problems.
        /// </summary>
        public static string program_message_error_connection {
            get {
                return ResourceManager.GetString("program_message_error_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently under test. Please wait.
        /// </summary>
        public static string program_message_error_exists {
            get {
                return ResourceManager.GetString("program_message_error_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omicron timed out.
        /// </summary>
        public static string program_message_error_omicron {
            get {
                return ResourceManager.GetString("program_message_error_omicron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under/over range value..
        /// </summary>
        public static string program_message_error_range {
            get {
                return ResourceManager.GetString("program_message_error_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string program_message_success {
            get {
                return ResourceManager.GetString("program_message_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register #.
        /// </summary>
        public static string register_watermark {
            get {
                return ResourceManager.GetString("register_watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Test.
        /// </summary>
        public static string startTest {
            get {
                return ResourceManager.GetString("startTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string tab_current {
            get {
                return ResourceManager.GetString("tab_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string tab_frequency {
            get {
                return ResourceManager.GetString("tab_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string tab_home {
            get {
                return ResourceManager.GetString("tab_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string tab_home_connect {
            get {
                return ResourceManager.GetString("tab_home_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethernet.
        /// </summary>
        public static string tab_home_ethernet {
            get {
                return ResourceManager.GetString("tab_home_ethernet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip Address.
        /// </summary>
        public static string tab_home_ipaddress {
            get {
                return ResourceManager.GetString("tab_home_ipaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string tab_home_port {
            get {
                return ResourceManager.GetString("tab_home_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial/USB.
        /// </summary>
        public static string tab_home_serial {
            get {
                return ResourceManager.GetString("tab_home_serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements.
        /// </summary>
        public static string tab_measurements {
            get {
                return ResourceManager.GetString("tab_measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total {0} item(s) found..
        /// </summary>
        public static string tab_message_found {
            get {
                return ResourceManager.GetString("tab_message_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        public static string tab_voltage {
            get {
                return ResourceManager.GetString("tab_voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metering.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
